// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import 'package:kinetic_ui_tokens/kinetic_ui_tokens.dart';

enum SpinnerSize { sm, md, lg, xl }

class KSpinner extends StatelessWidget {
  const KSpinner({
    super.key,
    this.size  = SpinnerSize.md,
    this.color,
  });

  final SpinnerSize size;
  final Color?      color;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;
    final (dim, stroke) = switch (size) {
      SpinnerSize.sm => (16.0, 2.0),
      SpinnerSize.md => (24.0, 2.5),
      SpinnerSize.lg => (32.0, 3.0),
      SpinnerSize.xl => (48.0, 3.5),
    };
    final fill = color ?? tokens.primary;

    return SizedBox(
      width: dim, height: dim,
      child: CircularProgressIndicator(
        strokeWidth:     stroke,
        color:           fill,
        backgroundColor: fill.withValues(alpha: 0.15),
        strokeCap:       StrokeCap.round,
      ),
    );
  }
}
