// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import '../../core/theme/kinetic_tokens.dart';

enum SeparatorOrientation { horizontal, vertical }

class KSeparator extends StatelessWidget {
  const KSeparator({
    super.key,
    this.orientation = SeparatorOrientation.horizontal,
    this.label,
    this.thickness = 1,
  });

  final SeparatorOrientation orientation;
  final String?              label;
  final double               thickness;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;

    if (orientation == SeparatorOrientation.vertical) {
      return VerticalDivider(width: thickness + 16, thickness: thickness, color: tokens.border);
    }

    if (label == null) {
      return Divider(height: thickness + 16, thickness: thickness, color: tokens.border);
    }

    return Row(
      children: [
        Expanded(child: Divider(thickness: thickness, color: tokens.border)),
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 12),
          child: Text(
            label!,
            style: TextStyle(fontSize: 12, color: tokens.onMuted),
          ),
        ),
        Expanded(child: Divider(thickness: thickness, color: tokens.border)),
      ],
    );
  }
}
