// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import '../../core/theme/kinetic_tokens.dart';

enum SeparatorOrientation { horizontal, vertical }
enum SeparatorVariant { default_, secondary, tertiary }

class KSeparator extends StatelessWidget {
  const KSeparator({
    super.key,
    this.orientation = SeparatorOrientation.horizontal,
    this.variant     = SeparatorVariant.default_,
    this.label,
    this.thickness   = 1,
  });

  final SeparatorOrientation orientation;
  final SeparatorVariant     variant;
  final String?              label;
  final double               thickness;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;
    final color = switch (variant) {
      SeparatorVariant.default_  => tokens.divider,
      SeparatorVariant.secondary => tokens.divider.withValues(alpha: 0.6),
      SeparatorVariant.tertiary  => tokens.divider.withValues(alpha: 0.3),
    };

    if (orientation == SeparatorOrientation.vertical) {
      return VerticalDivider(width: thickness + 16, thickness: thickness, color: color);
    }

    if (label == null) {
      return Divider(height: thickness + 20, thickness: thickness, color: color);
    }

    return Row(
      children: [
        Expanded(child: Divider(thickness: thickness, color: color)),
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 12),
          child: Text(label!, style: TextStyle(fontSize: 11, color: tokens.defaultForeground, fontWeight: FontWeight.w500, letterSpacing: 0.5)),
        ),
        Expanded(child: Divider(thickness: thickness, color: color)),
      ],
    );
  }
}
