// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import 'package:kinetic_ui_tokens/kinetic_ui_tokens.dart';

abstract final class KineticTheme {
  static ThemeData light() => ThemeData(
    useMaterial3:  true,
    colorScheme:   ColorScheme.fromSeed(
      seedColor:   const Color(0xFF09090B),
      brightness:  Brightness.light,
    ),
    extensions: const [KineticTokens.light],
    fontFamily: KTypography.fontFamily,
  );

  static ThemeData dark() => ThemeData(
    useMaterial3:  true,
    colorScheme:   ColorScheme.fromSeed(
      seedColor:   const Color(0xFFFAFAFA),
      brightness:  Brightness.dark,
    ),
    extensions: const [KineticTokens.dark],
    fontFamily: KTypography.fontFamily,
  );
}
