// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import 'package:kinetic_ui_tokens/kinetic_ui_tokens.dart';

enum RadioColor { default_, primary, secondary, success, warning, danger }

class KRadioOption<T> {
  const KRadioOption({
    required this.value,
    required this.label,
    this.description,
    this.isDisabled = false,
  });
  final T       value;
  final String  label;
  final String? description;
  final bool    isDisabled;
}

class KRadioGroup<T> extends StatelessWidget {
  const KRadioGroup({
    super.key,
    required this.value,
    required this.onChanged,
    required this.options,
    this.label,
    this.color       = RadioColor.primary,
    this.isDisabled  = false,
    this.isInvalid   = false,
    this.errorMessage,
  });

  final T                     value;
  final ValueChanged<T>?      onChanged;
  final List<KRadioOption<T>> options;
  final String?               label;
  final RadioColor            color;
  final bool                  isDisabled;
  final bool                  isInvalid;
  final String?               errorMessage;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;
    final active = isInvalid ? tokens.danger : _color(tokens);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      mainAxisSize: MainAxisSize.min,
      children: [
        if (label != null) ...[
          Text(label!, style: TextStyle(fontSize: 14, fontWeight: FontWeight.w500, color: tokens.foreground)),
          const SizedBox(height: 10),
        ],
        ...options.map((opt) {
          final selected = opt.value == value;
          final disabled = isDisabled || opt.isDisabled;
          return GestureDetector(
            onTap: disabled || onChanged == null ? null : () => onChanged!(opt.value),
            child: Opacity(
              opacity: disabled ? 0.5 : 1.0,
              child: Padding(
                padding: const EdgeInsets.only(bottom: 10),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    AnimatedContainer(
                      duration: const Duration(milliseconds: 150),
                      width: 20, height: 20,
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                        border: Border.all(color: selected ? active : tokens.divider, width: 1.5),
                      ),
                      child: selected
                          ? Center(
                              child: AnimatedContainer(
                                duration: const Duration(milliseconds: 150),
                                width: 10, height: 10,
                                decoration: BoxDecoration(shape: BoxShape.circle, color: active),
                              ),
                            )
                          : null,
                    ),
                    const SizedBox(width: 10),
                    Flexible(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Text(opt.label, style: TextStyle(fontSize: 14, fontWeight: FontWeight.w500, color: tokens.foreground)),
                          if (opt.description != null)
                            Text(opt.description!, style: TextStyle(fontSize: 12, color: tokens.defaultForeground, height: 1.4)),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
          );
        }),
        if (isInvalid && errorMessage != null)
          Text(errorMessage!, style: TextStyle(fontSize: 12, color: tokens.danger)),
      ],
    );
  }

  Color _color(KineticTokens t) => switch (color) {
    RadioColor.default_  => t.defaultForeground,
    RadioColor.primary   => t.primary,
    RadioColor.secondary => t.secondary,
    RadioColor.success   => t.success,
    RadioColor.warning   => t.warning,
    RadioColor.danger    => t.danger,
  };
}
