// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import 'package:kinetic_ui_tokens/kinetic_ui_tokens.dart';

enum SwitchSize  { sm, md, lg }
enum SwitchColor { default_, primary, secondary, success, warning, danger }

class KSwitch extends StatelessWidget {
  const KSwitch({
    super.key,
    required this.value,
    required this.onChanged,
    this.label,
    this.description,
    this.size        = SwitchSize.md,
    this.color       = SwitchColor.primary,
    this.isDisabled  = false,
    this.thumbIcon,
  });

  final bool               value;
  final ValueChanged<bool>? onChanged;
  final String?            label;
  final String?            description;
  final SwitchSize         size;
  final SwitchColor        color;
  final bool               isDisabled;
  final Widget?            thumbIcon;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;
    final active = _color(tokens);

    final (trackW, trackH, thumbD, thumbPad) = switch (size) {
      SwitchSize.sm => (36.0, 20.0, 14.0, 3.0),
      SwitchSize.md => (44.0, 24.0, 18.0, 3.0),
      SwitchSize.lg => (52.0, 28.0, 22.0, 3.0),
    };
    final fontSize = switch (size) {
      SwitchSize.sm => 13.0,
      SwitchSize.md => 14.0,
      SwitchSize.lg => 15.0,
    };
    final iconSize = switch (size) {
      SwitchSize.sm => 10.0,
      SwitchSize.md => 12.0,
      SwitchSize.lg => 14.0,
    };

    return GestureDetector(
      onTap: isDisabled || onChanged == null ? null : () => onChanged!(!value),
      child: Opacity(
        opacity: isDisabled ? 0.5 : 1.0,
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            AnimatedContainer(
              duration: const Duration(milliseconds: 200),
              curve: Curves.easeInOut,
              width: trackW, height: trackH,
              decoration: BoxDecoration(
                color:        value ? active : tokens.defaultColor,
                borderRadius: BorderRadius.circular(trackH / 2),
              ),
              child: AnimatedAlign(
                duration: const Duration(milliseconds: 200),
                curve: Curves.easeInOut,
                alignment: value ? Alignment.centerRight : Alignment.centerLeft,
                child: Padding(
                  padding: EdgeInsets.all(thumbPad),
                  child: Container(
                    width: thumbD, height: thumbD,
                    decoration: const BoxDecoration(
                      color: Colors.white,
                      shape: BoxShape.circle,
                      boxShadow: [BoxShadow(color: Colors.black12, blurRadius: 4, offset: Offset(0, 1))],
                    ),
                    alignment: Alignment.center,
                    child: thumbIcon != null
                        ? IconTheme(data: IconThemeData(size: iconSize, color: value ? active : tokens.defaultForeground), child: thumbIcon!)
                        : null,
                  ),
                ),
              ),
            ),
            if (label != null || description != null) ...[
              const SizedBox(width: 10),
              Flexible(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    if (label != null)
                      Text(label!, style: TextStyle(fontSize: fontSize, fontWeight: FontWeight.w500, color: tokens.foreground)),
                    if (description != null)
                      Text(description!, style: TextStyle(fontSize: fontSize - 1, color: tokens.defaultForeground, height: 1.4)),
                  ],
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }

  Color _color(KineticTokens t) => switch (color) {
    SwitchColor.default_  => t.defaultForeground,
    SwitchColor.primary   => t.primary,
    SwitchColor.secondary => t.secondary,
    SwitchColor.success   => t.success,
    SwitchColor.warning   => t.warning,
    SwitchColor.danger    => t.danger,
  };
}
