// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import 'package:kinetic_ui_tokens/kinetic_ui_tokens.dart';

enum AlertVariant { default_, accent, success, warning, danger }

class KAlert extends StatelessWidget {
  const KAlert({
    super.key,
    required this.description,
    this.title,
    this.variant  = AlertVariant.default_,
    this.icon,
    this.onClose,
    this.action,
  });

  final String       description;
  final String?      title;
  final AlertVariant variant;
  final IconData?    icon;
  final VoidCallback? onClose;
  final Widget?      action;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;

    final (accentColor, bgColor, borderColor) = switch (variant) {
      AlertVariant.default_ => (tokens.defaultForeground, tokens.defaultColor,                         tokens.divider),
      AlertVariant.accent   => (tokens.primary,           tokens.primary.withValues(alpha: 0.1),       tokens.primary.withValues(alpha: 0.25)),
      AlertVariant.success  => (tokens.success,           tokens.success.withValues(alpha: 0.1),       tokens.success.withValues(alpha: 0.25)),
      AlertVariant.warning  => (tokens.warning,           tokens.warning.withValues(alpha: 0.1),       tokens.warning.withValues(alpha: 0.25)),
      AlertVariant.danger   => (tokens.danger,            tokens.danger.withValues(alpha: 0.1),        tokens.danger.withValues(alpha: 0.25)),
    };

    final resolvedIcon = icon ?? switch (variant) {
      AlertVariant.default_ => Icons.info_outline,
      AlertVariant.accent   => Icons.info_outline,
      AlertVariant.success  => Icons.check_circle_outline,
      AlertVariant.warning  => Icons.warning_amber_outlined,
      AlertVariant.danger   => Icons.error_outline,
    };

    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color:        bgColor,
        border:       Border.all(color: borderColor),
        borderRadius: BorderRadius.circular(tokens.radiusMd),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.only(top: 1),
            child: Icon(resolvedIcon, size: 18, color: accentColor),
          ),
          const SizedBox(width: 10),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                if (title != null)
                  Padding(
                    padding: const EdgeInsets.only(bottom: 3),
                    child: Text(title!, style: TextStyle(fontSize: 14, fontWeight: FontWeight.w600, color: tokens.foreground)),
                  ),
                Text(description, style: TextStyle(fontSize: 13, color: tokens.foreground, height: 1.5)),
                if (action != null) ...[const SizedBox(height: 10), action!],
              ],
            ),
          ),
          if (onClose != null)
            GestureDetector(
              onTap: onClose,
              child: Padding(
                padding: const EdgeInsets.only(left: 8),
                child: Icon(Icons.close_rounded, size: 16, color: accentColor.withValues(alpha: 0.7)),
              ),
            ),
        ],
      ),
    );
  }
}
