// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import 'package:kinetic_ui_tokens/kinetic_ui_tokens.dart';

class KLabel extends StatelessWidget {
  const KLabel({
    super.key,
    required this.text,
    this.required = false,
    this.disabled = false,
  });

  final String text;
  final bool   required;
  final bool   disabled;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;

    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Text(
          text,
          style: TextStyle(
            fontSize:   14,
            fontWeight: FontWeight.w500,
            color:      disabled ? tokens.defaultForeground : null,
          ),
        ),
        if (required) ...[
          const SizedBox(width: 2),
          Text('*', style: TextStyle(color: tokens.danger, fontSize: 14)),
        ],
      ],
    );
  }
}
