// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import 'package:kinetic_ui_tokens/kinetic_ui_tokens.dart';

enum ChipVariant { solid, flat, bordered }
enum ChipColor   { default_, primary, secondary, success, warning, danger }
enum ChipSize    { sm, md, lg }

class KChip extends StatelessWidget {
  const KChip({
    super.key,
    required this.label,
    this.variant   = ChipVariant.flat,
    this.color     = ChipColor.default_,
    this.size      = ChipSize.md,
    this.startIcon,
    this.onClose,
    this.onTap,
  });

  final String        label;
  final ChipVariant   variant;
  final ChipColor     color;
  final ChipSize      size;
  final Widget?       startIcon;
  final VoidCallback? onClose;
  final VoidCallback? onTap;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;
    final base = _base(tokens);
    final fg   = _fg(tokens);

    final (bg, border) = switch (variant) {
      ChipVariant.solid    => (base,                         Colors.transparent),
      ChipVariant.flat     => (base.withValues(alpha: 0.15), Colors.transparent),
      ChipVariant.bordered => (Colors.transparent,           base),
    };
    final textColor = variant == ChipVariant.solid ? fg : base;

    final (hPad, vPad, fontSize, iconSize) = switch (size) {
      ChipSize.sm => (8.0,  2.0, 11.0, 12.0),
      ChipSize.md => (10.0, 4.0, 12.0, 14.0),
      ChipSize.lg => (14.0, 6.0, 14.0, 16.0),
    };

    Widget chip = Container(
      padding: EdgeInsets.symmetric(horizontal: hPad, vertical: vPad),
      decoration: BoxDecoration(
        color:        bg,
        border:       Border.all(color: border, width: border == Colors.transparent ? 0 : 1),
        borderRadius: BorderRadius.circular(9999),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        spacing: 4,
        children: [
          if (startIcon != null) IconTheme(data: IconThemeData(size: iconSize, color: textColor), child: startIcon!),
          Text(label, style: TextStyle(fontSize: fontSize, fontWeight: FontWeight.w500, color: textColor, height: 1.4)),
          if (onClose != null)
            GestureDetector(
              onTap: onClose,
              child: Icon(Icons.close_rounded, size: iconSize - 1, color: textColor.withValues(alpha: 0.7)),
            ),
        ],
      ),
    );

    if (onTap != null) return GestureDetector(onTap: onTap, child: chip);
    return chip;
  }

  Color _base(KineticTokens t) => switch (color) {
    ChipColor.default_  => t.defaultForeground,
    ChipColor.primary   => t.primary,
    ChipColor.secondary => t.secondary,
    ChipColor.success   => t.success,
    ChipColor.warning   => t.warning,
    ChipColor.danger    => t.danger,
  };

  Color _fg(KineticTokens t) => switch (color) {
    ChipColor.default_  => t.foreground,
    ChipColor.primary   => t.primaryForeground,
    ChipColor.secondary => t.secondaryForeground,
    ChipColor.success   => t.successForeground,
    ChipColor.warning   => t.warningForeground,
    ChipColor.danger    => t.dangerForeground,
  };
}
