// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import 'package:kinetic_ui_tokens/kinetic_ui_tokens.dart';

Future<T?> showKDialog<T>({
  required BuildContext context,
  required Widget child,
  bool barrierDismissible = true,
}) => showDialog<T>(
  context:              context,
  barrierDismissible:   barrierDismissible,
  barrierColor:         Colors.black54,
  builder:              (_) => child,
);

class KDialog extends StatelessWidget {
  const KDialog({
    super.key,
    this.title,
    this.description,
    required this.content,
    this.actions = const [],
    this.maxWidth = 512,
  });

  final Widget?       title;
  final Widget?       description;
  final Widget        content;
  final List<Widget>  actions;
  final double        maxWidth;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;

    return Dialog(
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(tokens.radiusLg),
        side:         BorderSide(color: tokens.border),
      ),
      child: ConstrainedBox(
        constraints: BoxConstraints(maxWidth: maxWidth),
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(
            mainAxisSize:       MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              if (title != null)
                DefaultTextStyle.merge(
                  style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w600),
                  child: title!,
                ),
              if (description != null) ...[
                const SizedBox(height: 8),
                DefaultTextStyle.merge(
                  style: TextStyle(fontSize: 14, color: tokens.onMuted),
                  child: description!,
                ),
              ],
              const SizedBox(height: 16),
              content,
              if (actions.isNotEmpty) ...[
                const SizedBox(height: 24),
                Row(
                  mainAxisAlignment: MainAxisAlignment.end,
                  spacing:           8,
                  children:          actions,
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }
}
