// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import 'package:kinetic_ui_tokens/kinetic_ui_tokens.dart';

enum ProgressColor { default_, primary, success, warning, danger }
enum ProgressSize  { sm, md, lg }

class KProgressBar extends StatelessWidget {
  const KProgressBar({
    super.key,
    required this.value,
    this.color           = ProgressColor.primary,
    this.size            = ProgressSize.md,
    this.label,
    this.showValue       = false,
    this.isIndeterminate = false,
    this.radius          = 9999,
  });

  final double        value;          // 0.0–1.0
  final ProgressColor color;
  final ProgressSize  size;
  final String?       label;
  final bool          showValue;
  final bool          isIndeterminate;
  final double        radius;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;
    final fill   = _color(tokens);
    final height = switch (size) { ProgressSize.sm => 4.0, ProgressSize.md => 6.0, ProgressSize.lg => 8.0 };

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      mainAxisSize: MainAxisSize.min,
      children: [
        if (label != null || showValue)
          Padding(
            padding: const EdgeInsets.only(bottom: 6),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                if (label != null)
                  Text(label!, style: TextStyle(fontSize: 13, fontWeight: FontWeight.w500, color: tokens.foreground)),
                if (showValue)
                  Text('${(value * 100).round()}%', style: TextStyle(fontSize: 12, color: tokens.defaultForeground)),
              ],
            ),
          ),
        ClipRRect(
          borderRadius: BorderRadius.circular(radius),
          child: SizedBox(
            height: height,
            child: LinearProgressIndicator(
              value:           isIndeterminate ? null : value.clamp(0.0, 1.0),
              backgroundColor: tokens.defaultColor,
              color:           fill,
            ),
          ),
        ),
      ],
    );
  }

  Color _color(KineticTokens t) => switch (color) {
    ProgressColor.default_ => t.defaultForeground,
    ProgressColor.primary  => t.primary,
    ProgressColor.success  => t.success,
    ProgressColor.warning  => t.warning,
    ProgressColor.danger   => t.danger,
  };
}

class KProgressCircle extends StatelessWidget {
  const KProgressCircle({
    super.key,
    required this.value,
    this.size            = 56.0,
    this.strokeWidth     = 5.0,
    this.color           = ProgressColor.primary,
    this.isIndeterminate = false,
    this.child,
  });

  final double        value;
  final double        size;
  final double        strokeWidth;
  final ProgressColor color;
  final bool          isIndeterminate;
  final Widget?       child;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;
    final fill = _color(tokens);

    return SizedBox(
      width: size, height: size,
      child: Stack(
        alignment: Alignment.center,
        children: [
          CircularProgressIndicator(
            value:           isIndeterminate ? null : value.clamp(0.0, 1.0),
            strokeWidth:     strokeWidth,
            color:           fill,
            backgroundColor: tokens.defaultColor,
            strokeCap:       StrokeCap.round,
          ),
          ?child,
        ],
      ),
    );
  }

  Color _color(KineticTokens t) => switch (color) {
    ProgressColor.default_ => t.defaultForeground,
    ProgressColor.primary  => t.primary,
    ProgressColor.success  => t.success,
    ProgressColor.warning  => t.warning,
    ProgressColor.danger   => t.danger,
  };
}
