// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import 'package:kinetic_ui_tokens/kinetic_ui_tokens.dart';

enum ToastVariant { info, success, warning, danger }

class KToast extends StatelessWidget {
  const KToast({
    super.key,
    required this.message,
    this.title,
    this.variant  = ToastVariant.info,
    this.action,
    this.onClose,
  });

  final String        message;
  final String?       title;
  final ToastVariant  variant;
  final Widget?       action;
  final VoidCallback? onClose;

  static void show(
    BuildContext context, {
    required String message,
    String?        title,
    ToastVariant   variant  = ToastVariant.info,
    Widget?        action,
    Duration       duration = const Duration(seconds: 4),
  }) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content:          KToast(message: message, title: title, variant: variant, action: action),
        backgroundColor:  Colors.transparent,
        elevation:        0,
        behavior:         SnackBarBehavior.floating,
        duration:         duration,
        padding:          const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;

    final (icon, iconColor) = switch (variant) {
      ToastVariant.info    => (Icons.info_outline,           tokens.primary),
      ToastVariant.success => (Icons.check_circle_outline,   tokens.success),
      ToastVariant.warning => (Icons.warning_amber_outlined, tokens.warning),
      ToastVariant.danger  => (Icons.error_outline,          tokens.danger),
    };

    return Container(
      padding:     const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      decoration:  BoxDecoration(
        color:        tokens.content1,
        border:       Border.all(color: tokens.divider),
        borderRadius: BorderRadius.circular(tokens.radiusMd),
        boxShadow: [
          BoxShadow(
            color:      Colors.black.withValues(alpha: 0.08),
            blurRadius: 12,
            offset:     const Offset(0, 4),
          ),
        ],
      ),
      child: Row(
        children: [
          Icon(icon, size: 20, color: iconColor),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize:       MainAxisSize.min,
              children: [
                if (title != null)
                  Text(title!, style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w600)),
                Text(message, style: const TextStyle(fontSize: 14)),
              ],
            ),
          ),
          if (action != null) ...[const SizedBox(width: 8), action!],
          if (onClose != null) ...[
            const SizedBox(width: 4),
            IconButton(
              onPressed: onClose,
              icon:      Icon(Icons.close, size: 16, color: tokens.defaultForeground),
              visualDensity: VisualDensity.compact,
            ),
          ],
        ],
      ),
    );
  }
}
