// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import 'package:kinetic_ui_tokens/kinetic_ui_tokens.dart';

class KInput extends StatelessWidget {
  const KInput({
    super.key,
    this.controller,
    this.focusNode,
    this.label,
    this.hint,
    this.helper,
    this.error,
    this.prefix,
    this.suffix,
    this.obscureText = false,
    this.enabled     = true,
    this.onChanged,
    this.onSubmitted,
    this.keyboardType,
    this.textInputAction,
    this.maxLines = 1,
  });

  final TextEditingController? controller;
  final FocusNode?             focusNode;
  final String?                label;
  final String?                hint;
  final String?                helper;
  final String?                error;
  final Widget?                prefix;
  final Widget?                suffix;
  final bool                   obscureText;
  final bool                   enabled;
  final ValueChanged<String>?  onChanged;
  final ValueChanged<String>?  onSubmitted;
  final TextInputType?         keyboardType;
  final TextInputAction?       textInputAction;
  final int                    maxLines;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;
    final hasError = error != null && error!.isNotEmpty;

    final borderColor = hasError ? tokens.destructive : tokens.border;
    final focusColor  = hasError ? tokens.destructive : tokens.ring;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      mainAxisSize: MainAxisSize.min,
      children: [
        if (label != null) ...[
          Text(
            label!,
            style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w500),
          ),
          const SizedBox(height: 6),
        ],
        TextField(
          controller:      controller,
          focusNode:       focusNode,
          obscureText:     obscureText,
          enabled:         enabled,
          onChanged:       onChanged,
          onSubmitted:     onSubmitted,
          keyboardType:    keyboardType,
          textInputAction: textInputAction,
          maxLines:        obscureText ? 1 : maxLines,
          style:           const TextStyle(fontSize: 14),
          decoration: InputDecoration(
            hintText:        hint,
            hintStyle:       TextStyle(fontSize: 14, color: tokens.onMuted),
            prefixIcon:      prefix,
            suffixIcon:      suffix,
            contentPadding:  const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
            filled:          true,
            fillColor:       enabled ? Colors.transparent : tokens.muted,
            enabledBorder:   _border(borderColor, tokens.radiusMd),
            focusedBorder:   _border(focusColor,  tokens.radiusMd, width: 2),
            errorBorder:     _border(tokens.destructive, tokens.radiusMd),
            focusedErrorBorder: _border(tokens.destructive, tokens.radiusMd, width: 2),
            disabledBorder:  _border(tokens.border, tokens.radiusMd),
          ),
        ),
        if (hasError) ...[
          const SizedBox(height: 4),
          Text(
            error!,
            style: TextStyle(fontSize: 12, color: tokens.destructive),
          ),
        ] else if (helper != null) ...[
          const SizedBox(height: 4),
          Text(
            helper!,
            style: TextStyle(fontSize: 12, color: tokens.onMuted),
          ),
        ],
      ],
    );
  }

  OutlineInputBorder _border(Color color, double radius, {double width = 1}) =>
      OutlineInputBorder(
        borderSide:   BorderSide(color: color, width: width),
        borderRadius: BorderRadius.circular(radius),
      );
}
