// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import '../../core/theme/kinetic_tokens.dart';

enum InputVariant { flat, bordered, faded, underlined }
enum InputSize    { sm, md, lg }
enum InputColor   { default_, primary, secondary, success, warning, danger }

class KInput extends StatefulWidget {
  const KInput({
    super.key,
    this.controller,
    this.focusNode,
    this.label,
    this.hint,
    this.helper,
    this.error,
    this.startContent,
    this.endContent,
    this.variant      = InputVariant.flat,
    this.size         = InputSize.md,
    this.color        = InputColor.primary,
    this.obscureText  = false,
    this.isDisabled   = false,
    this.isReadOnly   = false,
    this.onChanged,
    this.onSubmitted,
    this.keyboardType,
    this.textInputAction,
    this.maxLines     = 1,
  });

  final TextEditingController? controller;
  final FocusNode?             focusNode;
  final String?                label;
  final String?                hint;
  final String?                helper;
  final String?                error;
  final Widget?                startContent;
  final Widget?                endContent;
  final InputVariant           variant;
  final InputSize              size;
  final InputColor             color;
  final bool                   obscureText;
  final bool                   isDisabled;
  final bool                   isReadOnly;
  final ValueChanged<String>?  onChanged;
  final ValueChanged<String>?  onSubmitted;
  final TextInputType?         keyboardType;
  final TextInputAction?       textInputAction;
  final int                    maxLines;

  @override
  State<KInput> createState() => _KInputState();
}

class _KInputState extends State<KInput> {
  late final FocusNode _focus;
  bool _focused = false;

  @override
  void initState() {
    super.initState();
    _focus = widget.focusNode ?? FocusNode();
    _focus.addListener(() => setState(() => _focused = _focus.hasFocus));
  }

  @override
  void dispose() {
    if (widget.focusNode == null) _focus.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final tokens   = Theme.of(context).extension<KineticTokens>()!;
    final hasError = widget.error != null && widget.error!.isNotEmpty;

    final focusColor = hasError ? tokens.danger : _activeColor(tokens);

    final (vPad, fontSize, labelSize) = switch (widget.size) {
      InputSize.sm => (8.0,  13.0, 12.0),
      InputSize.md => (10.0, 14.0, 13.0),
      InputSize.lg => (13.0, 15.0, 14.0),
    };

    final (fillColor, borderEnabled, borderFocused, borderRadius) = switch (widget.variant) {
      InputVariant.flat       => (tokens.defaultColor,  Colors.transparent,                           Colors.transparent, tokens.radiusMd),
      InputVariant.bordered   => (Colors.transparent,   hasError ? tokens.danger : tokens.divider,    focusColor,         tokens.radiusMd),
      InputVariant.faded      => (tokens.content2,      hasError ? tokens.danger : tokens.content3,   focusColor,         tokens.radiusMd),
      InputVariant.underlined => (Colors.transparent,   hasError ? tokens.danger : tokens.divider,    focusColor,         0.0),
    };

    InputBorder makeBorder(Color color, {double width = 1}) {
      if (widget.variant == InputVariant.underlined) {
        return UnderlineInputBorder(borderSide: BorderSide(color: color, width: width));
      }
      return OutlineInputBorder(
        borderSide:   BorderSide(color: color, width: width),
        borderRadius: BorderRadius.circular(borderRadius),
      );
    }

    final isFlat = widget.variant == InputVariant.flat;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      mainAxisSize: MainAxisSize.min,
      children: [
        if (widget.label != null) ...[
          Text(widget.label!, style: TextStyle(fontSize: labelSize, fontWeight: FontWeight.w500, color: tokens.foreground)),
          const SizedBox(height: 6),
        ],
        TextField(
          controller:      widget.controller,
          focusNode:       _focus,
          obscureText:     widget.obscureText,
          enabled:         !widget.isDisabled,
          readOnly:        widget.isReadOnly,
          onChanged:       widget.onChanged,
          onSubmitted:     widget.onSubmitted,
          keyboardType:    widget.keyboardType,
          textInputAction: widget.textInputAction,
          maxLines:        widget.obscureText ? 1 : widget.maxLines,
          style:           TextStyle(fontSize: fontSize),
          decoration: InputDecoration(
            hintText:      widget.hint,
            hintStyle:     TextStyle(fontSize: fontSize, color: tokens.defaultForeground),
            prefixIcon:    widget.startContent,
            suffixIcon:    widget.endContent,
            contentPadding: EdgeInsets.symmetric(horizontal: 12, vertical: vPad),
            filled:         true,
            fillColor:      widget.isDisabled ? tokens.content2 : (isFlat && _focused ? tokens.content2 : fillColor),
            enabledBorder:  makeBorder(isFlat ? Colors.transparent : borderEnabled),
            focusedBorder:  makeBorder(isFlat ? Colors.transparent : borderFocused, width: 2),
            errorBorder:    makeBorder(tokens.danger),
            focusedErrorBorder: makeBorder(tokens.danger, width: 2),
            disabledBorder: makeBorder(Colors.transparent),
          ),
        ),
        if (hasError) ...[
          const SizedBox(height: 4),
          Text(widget.error!, style: TextStyle(fontSize: 12, color: tokens.danger)),
        ] else if (widget.helper != null) ...[
          const SizedBox(height: 4),
          Text(widget.helper!, style: TextStyle(fontSize: 12, color: tokens.defaultForeground)),
        ],
      ],
    );
  }

  Color _activeColor(KineticTokens t) => switch (widget.color) {
    InputColor.default_  => t.defaultForeground,
    InputColor.primary   => t.primary,
    InputColor.secondary => t.secondary,
    InputColor.success   => t.success,
    InputColor.warning   => t.warning,
    InputColor.danger    => t.danger,
  };
}
