// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import 'package:kinetic_ui_tokens/kinetic_ui_tokens.dart';

class KSkeleton extends StatefulWidget {
  const KSkeleton({
    super.key,
    this.width,
    this.height = 16,
    this.borderRadius,
    this.isCircle = false,
  });

  final double? width;
  final double  height;
  final double? borderRadius;
  final bool    isCircle;

  @override
  State<KSkeleton> createState() => _KSkeletonState();
}

class _KSkeletonState extends State<KSkeleton>
    with SingleTickerProviderStateMixin {
  late final AnimationController _ctrl;
  late final Animation<double>   _anim;

  @override
  void initState() {
    super.initState();
    _ctrl = AnimationController(
      vsync:    this,
      duration: const Duration(milliseconds: 1400),
    )..repeat(reverse: true);
    _anim = CurvedAnimation(parent: _ctrl, curve: Curves.easeInOut);
  }

  @override
  void dispose() {
    _ctrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final tokens  = Theme.of(context).extension<KineticTokens>()!;
    final radius  = widget.isCircle
        ? BorderRadius.circular(9999)
        : BorderRadius.circular(widget.borderRadius ?? tokens.radiusMd);

    return AnimatedBuilder(
      animation: _anim,
      builder: (context, _) => Container(
        width:  widget.isCircle ? widget.height : widget.width,
        height: widget.height,
        decoration: BoxDecoration(
          borderRadius: radius,
          color: Color.lerp(tokens.defaultColor, tokens.divider, _anim.value),
        ),
      ),
    );
  }
}
