// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import 'package:kinetic_ui_tokens/kinetic_ui_tokens.dart';

enum AvatarSize   { sm, md, lg }
enum AvatarColor  { default_, primary, secondary, success, warning, danger }
enum AvatarRadius { none, sm, md, lg, full }

class KAvatar extends StatelessWidget {
  const KAvatar({
    super.key,
    this.imageUrl,
    this.initials,
    this.icon,
    this.size            = AvatarSize.md,
    this.color           = AvatarColor.default_,
    this.radius          = AvatarRadius.full,
    this.isBordered      = false,
    this.backgroundColor,
  });

  final String?      imageUrl;
  final String?      initials;
  final Widget?      icon;
  final AvatarSize   size;
  final AvatarColor  color;
  final AvatarRadius radius;
  final bool         isBordered;
  final Color?       backgroundColor;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;
    final dim      = switch (size) { AvatarSize.sm => 32.0, AvatarSize.md => 40.0, AvatarSize.lg => 56.0 };
    final fontSize = switch (size) { AvatarSize.sm => 12.0, AvatarSize.md => 14.0, AvatarSize.lg => 18.0 };
    final iconSize = switch (size) { AvatarSize.sm => 16.0, AvatarSize.md => 20.0, AvatarSize.lg => 28.0 };

    final r = switch (radius) {
      AvatarRadius.none => 0.0,
      AvatarRadius.sm   => 6.0,
      AvatarRadius.md   => 10.0,
      AvatarRadius.lg   => 14.0,
      AvatarRadius.full => dim / 2,
    };

    final bg = backgroundColor ?? _bgColor(tokens);
    final fg = _fgColor(tokens);

    Widget content;
    if (imageUrl != null) {
      content = Image.network(
        imageUrl!, width: dim, height: dim, fit: BoxFit.cover,
        errorBuilder: (_, _, _) => _fallback(bg, fg, fontSize, iconSize),
      );
    } else {
      content = _fallback(bg, fg, fontSize, iconSize);
    }

    Widget avatar = ClipRRect(
      borderRadius: BorderRadius.circular(r),
      child: SizedBox(width: dim, height: dim, child: content),
    );

    if (isBordered) {
      final borderColor = switch (color) {
        AvatarColor.default_  => tokens.defaultForeground,
        AvatarColor.primary   => tokens.primary,
        AvatarColor.secondary => tokens.secondary,
        AvatarColor.success   => tokens.success,
        AvatarColor.warning   => tokens.warning,
        AvatarColor.danger    => tokens.danger,
      };
      avatar = Container(
        width: dim + 4, height: dim + 4,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(r + 2),
          border: Border.all(color: borderColor, width: 2),
        ),
        child: Padding(padding: const EdgeInsets.all(2), child: avatar),
      );
    }
    return avatar;
  }

  Widget _fallback(Color bg, Color fg, double fontSize, double iconSize) {
    return Container(
      color: bg, alignment: Alignment.center,
      child: initials != null
          ? Text(
              initials!.substring(0, initials!.length.clamp(0, 2)).toUpperCase(),
              style: TextStyle(fontSize: fontSize, fontWeight: FontWeight.w600, color: fg),
            )
          : icon != null
              ? IconTheme(data: IconThemeData(size: iconSize, color: fg), child: icon!)
              : Icon(Icons.person, size: iconSize, color: fg),
    );
  }

  Color _bgColor(KineticTokens t) => switch (color) {
    AvatarColor.default_  => t.defaultColor,
    AvatarColor.primary   => t.primary,
    AvatarColor.secondary => t.secondary,
    AvatarColor.success   => t.success,
    AvatarColor.warning   => t.warning,
    AvatarColor.danger    => t.danger,
  };

  Color _fgColor(KineticTokens t) => switch (color) {
    AvatarColor.default_  => t.foreground,
    AvatarColor.primary   => t.primaryForeground,
    AvatarColor.secondary => t.secondaryForeground,
    AvatarColor.success   => t.successForeground,
    AvatarColor.warning   => t.warningForeground,
    AvatarColor.danger    => t.dangerForeground,
  };
}
