// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import '../../core/theme/kinetic_tokens.dart';

enum TabVariant { primary, secondary }

class KTabItem {
  const KTabItem({required this.label, this.icon});
  final String  label;
  final Widget? icon;
}

class KTabs extends StatefulWidget {
  const KTabs({
    super.key,
    required this.tabs,
    required this.children,
    this.variant      = TabVariant.primary,
    this.initialIndex = 0,
    this.onChanged,
  });

  final List<KTabItem> tabs;
  final List<Widget>   children;
  final TabVariant     variant;
  final int            initialIndex;
  final ValueChanged<int>? onChanged;

  @override
  State<KTabs> createState() => _KTabsState();
}

class _KTabsState extends State<KTabs> {
  late int _index;

  @override
  void initState() {
    super.initState();
    _index = widget.initialIndex;
  }

  void _select(int i) {
    if (i == _index) return;
    setState(() => _index = i);
    widget.onChanged?.call(i);
  }

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        widget.variant == TabVariant.primary
            ? _PrimaryBar(tabs: widget.tabs, index: _index, onTap: _select, tokens: tokens)
            : _SecondaryBar(tabs: widget.tabs, index: _index, onTap: _select, tokens: tokens),
        const SizedBox(height: 16),
        widget.children[_index],
      ],
    );
  }
}

class _PrimaryBar extends StatelessWidget {
  const _PrimaryBar({required this.tabs, required this.index, required this.onTap, required this.tokens});
  final List<KTabItem>     tabs;
  final int                index;
  final void Function(int) onTap;
  final KineticTokens      tokens;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(4),
      decoration: BoxDecoration(color: tokens.defaultColor, borderRadius: BorderRadius.circular(10)),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: List.generate(tabs.length, (i) {
          final active = i == index;
          final tab = tabs[i];
          return GestureDetector(
            onTap: () => onTap(i),
            child: AnimatedContainer(
              duration: const Duration(milliseconds: 200),
              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 7),
              decoration: BoxDecoration(
                color:        active ? tokens.content1 : Colors.transparent,
                borderRadius: BorderRadius.circular(7),
                boxShadow:    active ? [BoxShadow(color: Colors.black.withValues(alpha: 0.06), blurRadius: 4, offset: const Offset(0, 1))] : null,
              ),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                spacing: 6,
                children: [
                  if (tab.icon != null)
                    IconTheme(data: IconThemeData(size: 15, color: active ? tokens.foreground : tokens.defaultForeground), child: tab.icon!),
                  Text(
                    tab.label,
                    style: TextStyle(
                      fontSize: 13, height: 1,
                      fontWeight: active ? FontWeight.w600 : FontWeight.w400,
                      color: active ? tokens.foreground : tokens.defaultForeground,
                    ),
                  ),
                ],
              ),
            ),
          );
        }),
      ),
    );
  }
}

class _SecondaryBar extends StatelessWidget {
  const _SecondaryBar({required this.tabs, required this.index, required this.onTap, required this.tokens});
  final List<KTabItem>     tabs;
  final int                index;
  final void Function(int) onTap;
  final KineticTokens      tokens;

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisSize: MainAxisSize.min,
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          mainAxisSize: MainAxisSize.min,
          children: List.generate(tabs.length, (i) {
            final active = i == index;
            final tab = tabs[i];
            return GestureDetector(
              onTap: () => onTap(i),
              child: Padding(
                padding: const EdgeInsets.only(right: 24),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Padding(
                      padding: const EdgeInsets.only(bottom: 8),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        spacing: 6,
                        children: [
                          if (tab.icon != null)
                            IconTheme(data: IconThemeData(size: 15, color: active ? tokens.primary : tokens.defaultForeground), child: tab.icon!),
                          Text(
                            tab.label,
                            style: TextStyle(
                              fontSize: 14,
                              fontWeight: active ? FontWeight.w600 : FontWeight.w400,
                              color: active ? tokens.primary : tokens.defaultForeground,
                            ),
                          ),
                        ],
                      ),
                    ),
                    AnimatedContainer(
                      duration: const Duration(milliseconds: 200),
                      height: 2, width: 40,
                      decoration: BoxDecoration(
                        color:        active ? tokens.primary : Colors.transparent,
                        borderRadius: BorderRadius.circular(1),
                      ),
                    ),
                  ],
                ),
              ),
            );
          }),
        ),
        Divider(height: 1, color: tokens.divider),
      ],
    );
  }
}
