// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import 'package:kinetic_ui_tokens/kinetic_ui_tokens.dart';

enum BadgeVariant { primary, secondary, outline, destructive }

class KBadge extends StatelessWidget {
  const KBadge({
    super.key,
    required this.label,
    this.variant = BadgeVariant.primary,
    this.icon,
  });

  final String       label;
  final BadgeVariant variant;
  final Widget?      icon;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;

    final (bg, fg, border) = switch (variant) {
      BadgeVariant.primary     => (tokens.primary,     tokens.onPrimary,     Colors.transparent),
      BadgeVariant.secondary   => (tokens.muted,        tokens.primary,       Colors.transparent),
      BadgeVariant.outline     => (Colors.transparent, tokens.primary,       tokens.border),
      BadgeVariant.destructive => (tokens.destructive, tokens.onDestructive, Colors.transparent),
    };

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 2),
      decoration: BoxDecoration(
        color:        bg,
        border:       Border.all(color: border),
        borderRadius: BorderRadius.circular(9999),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        spacing: 4,
        children: [
          if (icon != null)
            IconTheme(
              data: IconThemeData(size: 12, color: fg),
              child: icon!,
            ),
          Text(
            label,
            style: TextStyle(
              fontSize:   12,
              fontWeight: FontWeight.w500,
              color:      fg,
              height:     1.5,
            ),
          ),
        ],
      ),
    );
  }
}
