// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import '../../core/theme/kinetic_tokens.dart';

enum ButtonVariant { solid, outline, ghost, destructive }
enum ButtonSize    { sm, md, lg }

class KButton extends StatelessWidget {
  const KButton({
    super.key,
    required this.child,
    this.onPressed,
    this.variant   = ButtonVariant.solid,
    this.size      = ButtonSize.md,
    this.leading,
    this.trailing,
    this.isLoading = false,
    this.fullWidth = false,
  });

  final Widget        child;
  final VoidCallback? onPressed;
  final ButtonVariant variant;
  final ButtonSize    size;
  final Widget?       leading;
  final Widget?       trailing;
  final bool          isLoading;
  final bool          fullWidth;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;

    final (bgColor, fgColor, borderColor) = switch (variant) {
      ButtonVariant.solid       => (tokens.primary,     tokens.onPrimary,     Colors.transparent),
      ButtonVariant.outline     => (Colors.transparent, tokens.primary,       tokens.border),
      ButtonVariant.ghost       => (Colors.transparent, tokens.primary,       Colors.transparent),
      ButtonVariant.destructive => (tokens.destructive, tokens.onDestructive, Colors.transparent),
    };

    final (height, hPad, fontSize) = switch (size) {
      ButtonSize.sm => (32.0, 12.0, 13.0),
      ButtonSize.md => (40.0, 16.0, 14.0),
      ButtonSize.lg => (48.0, 20.0, 16.0),
    };

    return SizedBox(
      width: fullWidth ? double.infinity : null,
      height: height,
      child: FilledButton(
        onPressed: isLoading ? null : onPressed,
        style: FilledButton.styleFrom(
          backgroundColor: bgColor,
          foregroundColor: fgColor,
          disabledBackgroundColor: bgColor.withValues(alpha: 0.5),
          padding:    EdgeInsets.symmetric(horizontal: hPad),
          side:       BorderSide(color: borderColor),
          shape:      RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(tokens.radiusMd),
          ),
          textStyle: TextStyle(fontSize: fontSize, fontWeight: FontWeight.w500),
        ),
        child: isLoading
          ? SizedBox.square(
              dimension: fontSize,
              child: CircularProgressIndicator(strokeWidth: 2, color: fgColor),
            )
          : Row(
              mainAxisSize: MainAxisSize.min,
              spacing: 8,
              children: [
                ?leading,
                child,
                ?trailing,
              ],
            ),
      ),
    );
  }
}
