// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import '../../core/theme/kinetic_tokens.dart';

enum ButtonVariant { solid, flat, bordered, outline, shadow, faded }
enum ButtonColor   { default_, primary, secondary, success, warning, danger }
enum ButtonSize    { sm, md, lg }
enum ButtonRadius  { none, sm, md, lg, full }

class KButton extends StatelessWidget {
  const KButton({
    super.key,
    required this.child,
    this.onPressed,
    this.variant      = ButtonVariant.solid,
    this.color        = ButtonColor.primary,
    this.size         = ButtonSize.md,
    this.radius,
    this.startContent,
    this.endContent,
    this.isLoading    = false,
    this.fullWidth    = false,
    this.isIconOnly   = false,
    this.isDisabled   = false,
  });

  final Widget        child;
  final VoidCallback? onPressed;
  final ButtonVariant variant;
  final ButtonColor   color;
  final ButtonSize    size;
  final ButtonRadius? radius;
  final Widget?       startContent;
  final Widget?       endContent;
  final bool          isLoading;
  final bool          fullWidth;
  final bool          isIconOnly;
  final bool          isDisabled;

  @override
  Widget build(BuildContext context) {
    final tokens  = Theme.of(context).extension<KineticTokens>()!;
    final base    = _base(tokens);
    final fg      = _fg(tokens);

    final (bgColor, fgColor, borderColor, hasShadow) = switch (variant) {
      ButtonVariant.solid    => (base,               fg,   Colors.transparent, false),
      ButtonVariant.flat     => (base.withValues(alpha: 0.15), base, Colors.transparent, false),
      ButtonVariant.bordered => (Colors.transparent, base, base,               false),
      ButtonVariant.outline  => (Colors.transparent, base, base,               false),
      ButtonVariant.shadow   => (base,               fg,   Colors.transparent, true),
      ButtonVariant.faded    => (tokens.content2,    base, tokens.content3,    false),
    };

    final (height, hPad, iconPad, fontSize) = switch (size) {
      ButtonSize.sm => (32.0, isIconOnly ?  8.0 : 12.0,  8.0, 12.0),
      ButtonSize.md => (40.0, isIconOnly ? 10.0 : 16.0, 10.0, 14.0),
      ButtonSize.lg => (48.0, isIconOnly ? 14.0 : 24.0, 14.0, 16.0),
    };

    final r = switch (radius) {
      ButtonRadius.none => 0.0,
      ButtonRadius.sm   => 6.0,
      ButtonRadius.md   => 8.0,
      ButtonRadius.lg   => 12.0,
      ButtonRadius.full => 9999.0,
      null              => 9999.0,
    };

    final List<BoxShadow> shadows = hasShadow
        ? [BoxShadow(color: base.withValues(alpha: 0.4), blurRadius: 12, offset: const Offset(0, 4))]
        : [];

    final effectiveDisabled = isDisabled || (onPressed == null && !isLoading);

    Widget content;
    if (isLoading) {
      content = SizedBox.square(
        dimension: fontSize + 2,
        child: CircularProgressIndicator(strokeWidth: 2, color: fgColor),
      );
    } else if (isIconOnly) {
      content = IconTheme(data: IconThemeData(size: fontSize + 2, color: fgColor), child: child);
    } else {
      content = Row(
        mainAxisSize: MainAxisSize.min,
        spacing: 6,
        children: [
          if (startContent != null)
            IconTheme(data: IconThemeData(size: fontSize, color: fgColor), child: startContent!),
          DefaultTextStyle.merge(
            style: TextStyle(fontSize: fontSize, fontWeight: FontWeight.w500, color: fgColor),
            child: child,
          ),
          if (endContent != null)
            IconTheme(data: IconThemeData(size: fontSize, color: fgColor), child: endContent!),
        ],
      );
    }

    final borderSide = borderColor == Colors.transparent
        ? BorderSide.none
        : BorderSide(color: borderColor, width: variant == ButtonVariant.outline ? 1.5 : 1.0);

    Widget button = SizedBox(
      width:  fullWidth ? double.infinity : (isIconOnly ? height : null),
      height: height,
      child: FilledButton(
        onPressed: (isLoading || effectiveDisabled) ? null : onPressed,
        style: FilledButton.styleFrom(
          backgroundColor:         shadows.isEmpty ? bgColor : Colors.transparent,
          foregroundColor:         fgColor,
          disabledBackgroundColor: bgColor.withValues(alpha: 0.5),
          disabledForegroundColor: fgColor.withValues(alpha: 0.5),
          padding:   EdgeInsets.symmetric(horizontal: isIconOnly ? iconPad : hPad),
          side:      borderSide,
          shape:     RoundedRectangleBorder(borderRadius: BorderRadius.circular(r)),
          textStyle: TextStyle(fontSize: fontSize, fontWeight: FontWeight.w500),
          elevation: 0,
          shadowColor: Colors.transparent,
        ),
        child: content,
      ),
    );

    if (shadows.isNotEmpty) {
      button = DecoratedBox(
        decoration: BoxDecoration(
          color:        bgColor,
          borderRadius: BorderRadius.circular(r),
          boxShadow:    shadows,
        ),
        child: button,
      );
      button = SizedBox(
        width:  fullWidth ? double.infinity : (isIconOnly ? height : null),
        height: height,
        child: button,
      );
    }

    if (effectiveDisabled && !isLoading) {
      button = Opacity(opacity: 0.5, child: button);
    }

    return button;
  }

  Color _base(KineticTokens t) => switch (color) {
    ButtonColor.default_  => t.defaultForeground,
    ButtonColor.primary   => t.primary,
    ButtonColor.secondary => t.secondary,
    ButtonColor.success   => t.success,
    ButtonColor.warning   => t.warning,
    ButtonColor.danger    => t.danger,
  };

  Color _fg(KineticTokens t) => switch (color) {
    ButtonColor.default_  => t.background,
    ButtonColor.primary   => t.primaryForeground,
    ButtonColor.secondary => t.secondaryForeground,
    ButtonColor.success   => t.successForeground,
    ButtonColor.warning   => t.warningForeground,
    ButtonColor.danger    => t.dangerForeground,
  };
}
