// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import '../../core/theme/kinetic_tokens.dart';

class KSlider extends StatelessWidget {
  const KSlider({
    super.key,
    required this.value,
    required this.onChanged,
    this.min        = 0.0,
    this.max        = 100.0,
    this.divisions,
    this.label,
    this.startLabel,
    this.endLabel,
    this.showValue  = true,
    this.isDisabled = false,
    this.color,
  });

  final double             value;
  final ValueChanged<double>? onChanged;
  final double             min;
  final double             max;
  final int?               divisions;
  final String?            label;
  final String?            startLabel;
  final String?            endLabel;
  final bool               showValue;
  final bool               isDisabled;
  final Color?             color;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;
    final fill   = color ?? tokens.primary;
    final display = value.toStringAsFixed(value.truncateToDouble() == value ? 0 : 1);

    return Opacity(
      opacity: isDisabled ? 0.5 : 1.0,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          if (label != null || showValue)
            Padding(
              padding: const EdgeInsets.only(bottom: 2),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  if (label != null)
                    Text(label!, style: TextStyle(fontSize: 14, fontWeight: FontWeight.w500, color: tokens.foreground)),
                  if (showValue)
                    Text(display, style: TextStyle(fontSize: 13, fontWeight: FontWeight.w500, color: tokens.defaultForeground)),
                ],
              ),
            ),
          SliderTheme(
            data: SliderTheme.of(context).copyWith(
              activeTrackColor:    fill,
              inactiveTrackColor:  tokens.defaultColor,
              thumbColor:          fill,
              overlayColor:        fill.withValues(alpha: 0.12),
              trackHeight:         4,
              thumbShape:          const RoundSliderThumbShape(enabledThumbRadius: 10),
              overlayShape:        const RoundSliderOverlayShape(overlayRadius: 20),
              activeTickMarkColor:   Colors.transparent,
              inactiveTickMarkColor: Colors.transparent,
            ),
            child: Slider(
              value:     value.clamp(min, max),
              min:       min,
              max:       max,
              divisions: divisions,
              onChanged: isDisabled ? null : onChanged,
            ),
          ),
          if (startLabel != null || endLabel != null)
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 10),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(startLabel ?? '', style: TextStyle(fontSize: 11, color: tokens.defaultForeground)),
                  Text(endLabel   ?? '', style: TextStyle(fontSize: 11, color: tokens.defaultForeground)),
                ],
              ),
            ),
        ],
      ),
    );
  }
}
