// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import 'package:kinetic_ui_tokens/kinetic_ui_tokens.dart';

enum CheckboxSize  { sm, md, lg }
enum CheckboxColor { default_, primary, secondary, success, warning, danger }

class KCheckbox extends StatelessWidget {
  const KCheckbox({
    super.key,
    required this.value,
    required this.onChanged,
    this.label,
    this.description,
    this.size        = CheckboxSize.md,
    this.color       = CheckboxColor.primary,
    this.isDisabled  = false,
    this.isInvalid   = false,
  });

  final bool               value;
  final ValueChanged<bool>? onChanged;
  final String?            label;
  final String?            description;
  final CheckboxSize       size;
  final CheckboxColor      color;
  final bool               isDisabled;
  final bool               isInvalid;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;
    final active   = isInvalid ? tokens.danger : _color(tokens);
    final boxSize  = switch (size) { CheckboxSize.sm => 16.0, CheckboxSize.md => 20.0, CheckboxSize.lg => 24.0 };
    final fontSize = switch (size) { CheckboxSize.sm => 13.0, CheckboxSize.md => 14.0, CheckboxSize.lg => 15.0 };

    return GestureDetector(
      onTap: isDisabled || onChanged == null ? null : () => onChanged!(!value),
      child: Opacity(
        opacity: isDisabled ? 0.5 : 1.0,
        child: Row(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AnimatedContainer(
              duration: const Duration(milliseconds: 150),
              width: boxSize, height: boxSize,
              decoration: BoxDecoration(
                color:        value ? active : Colors.transparent,
                border:       Border.all(color: value ? active : (isInvalid ? tokens.danger : tokens.divider), width: 1.5),
                borderRadius: BorderRadius.circular(4),
              ),
              child: value ? Icon(Icons.check_rounded, size: boxSize * 0.68, color: Colors.white) : null,
            ),
            if (label != null || description != null) ...[
              const SizedBox(width: 8),
              Flexible(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    if (label != null)
                      Text(label!, style: TextStyle(fontSize: fontSize, fontWeight: FontWeight.w500, color: tokens.foreground)),
                    if (description != null)
                      Text(description!, style: TextStyle(fontSize: fontSize - 1, color: tokens.defaultForeground, height: 1.4)),
                  ],
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }

  Color _color(KineticTokens t) => switch (color) {
    CheckboxColor.default_  => t.defaultForeground,
    CheckboxColor.primary   => t.primary,
    CheckboxColor.secondary => t.secondary,
    CheckboxColor.success   => t.success,
    CheckboxColor.warning   => t.warning,
    CheckboxColor.danger    => t.danger,
  };
}
