// Generated by kinetic_ui — free to modify
import 'package:flutter/material.dart';
import '../../core/theme/kinetic_tokens.dart';

class KCard extends StatelessWidget {
  const KCard({
    super.key,
    this.child,
    this.header,
    this.footer,
    this.padding,
    this.onTap,
  });

  final Widget?      child;
  final Widget?      header;
  final Widget?      footer;
  final EdgeInsets?  padding;
  final VoidCallback? onTap;

  @override
  Widget build(BuildContext context) {
    final tokens = Theme.of(context).extension<KineticTokens>()!;

    final card = Container(
      decoration: BoxDecoration(
        color:        Theme.of(context).colorScheme.surface,
        border:       Border.all(color: tokens.border),
        borderRadius: BorderRadius.circular(tokens.radiusLg),
        boxShadow: [
          BoxShadow(
            color:       Colors.black.withValues(alpha: 0.04),
            blurRadius:  4,
            offset:      const Offset(0, 1),
          ),
        ],
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          if (header != null)
            Padding(
              padding: padding ?? const EdgeInsets.fromLTRB(24, 24, 24, 0),
              child: header,
            ),
          if (child != null)
            Padding(
              padding: padding ?? const EdgeInsets.all(24),
              child: child,
            ),
          if (footer != null) ...[
            Divider(height: 1, color: tokens.border),
            Padding(
              padding: padding ?? const EdgeInsets.fromLTRB(24, 16, 24, 16),
              child: footer,
            ),
          ],
        ],
      ),
    );

    return onTap != null
        ? InkWell(
            onTap: onTap,
            borderRadius: BorderRadius.circular(tokens.radiusLg),
            child: card,
          )
        : card;
  }
}

class KCardHeader extends StatelessWidget {
  const KCardHeader({super.key, required this.title, this.subtitle, this.action});

  final Widget  title;
  final Widget? subtitle;
  final Widget? action;

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              DefaultTextStyle.merge(
                style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w600),
                child: title,
              ),
              if (subtitle != null) ...[
                const SizedBox(height: 4),
                DefaultTextStyle.merge(
                  style: TextStyle(
                    fontSize: 14,
                    color: Theme.of(context).extension<KineticTokens>()!.onMuted,
                  ),
                  child: subtitle!,
                ),
              ],
            ],
          ),
        ),
        if (action != null) action!,
      ],
    );
  }
}
